services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: starwars-app
    restart: unless-stopped
    working_dir: /app/app
    volumes:
      - ./:/app
    networks:
      - starwars-network
    environment:
      - RUN_TESTS=true

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: starwars-queue
    restart: unless-stopped
    working_dir: /app/app
    volumes:
      - ./:/app
      - ./docker/queue-init.sh:/usr/local/bin/queue-init.sh
    networks:
      - starwars-network
    environment:
      - XDEBUG_MODE=off
    entrypoint: []
    command: bash -c "chmod +x /usr/local/bin/queue-init.sh && /usr/local/bin/queue-init.sh"

  nginx:
    image: nginx:alpine
    container_name: starwars-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - starwars-network
    depends_on:
      - app

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: starwars-node
    volumes:
      - ./:/app
    working_dir: /app/app
    networks:
      - starwars-network
    tty: true
    restart: "no"
    entrypoint: ["/usr/local/bin/entrypoint-dev.sh"]

networks:
  starwars-network:
    driver: bridge