version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: starwars-app
    restart: unless-stopped
    working_dir: /app/app
    volumes:
      - ./:/app
    networks:
      - starwars-network
    environment:
      - XDEBUG_MODE=coverage
      - RUN_TESTS=false
    command: php-fpm

  nginx:
    image: nginx:alpine
    container_name: starwars-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - starwars-network
    depends_on:
      - app

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: starwars-node
    volumes:
      - ./:/app
    working_dir: /app/app
    networks:
      - starwars-network
    environment:
      - DEBUG=true
    tty: true
    # Set to run once and exit
    restart: "no"

networks:
  starwars-network:
    driver: bridge