version: '3.8'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: starwars-app
    restart: unless-stopped
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    networks:
      - starwars-network
    environment:
      - XDEBUG_MODE=coverage
    depends_on:
      - node

  nginx:
    image: nginx:alpine
    container_name: starwars-nginx
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - ./:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - starwars-network
    depends_on:
      - app

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: starwars-node
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - starwars-network
    ports:
    - "5173:5173"
    tty: true

networks:
  starwars-network:
    driver: bridge